#logging:
#  level:
#    root: debug
#server:
#  servlet:
#    session:
#      timeout: 60
management:
  endpoints:
    web:
      expose: metrics
---
spring:
  profiles: dev
server:
  port: 1234
---
spring:
  profiles: proxy
server:
  servlet:
    context-path: /api
